amad=read.delim("clipboard")
View(amad)
str(amad)
mean(amad$volume)
t.test(amad$volume,mu=10)

amad=read.delim("clipboard")
View(amad)
str(amad)
mean(amad$pendapatan)
t.test(amad$pendapatan,mu=14500)
